run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

linters-settings:
  cyclop:
    max-complexity: 10
    skip-tests: true
  
  gocyclo:
    min-complexity: 10
  
  gocognit:
    min-complexity: 10
  
  dupl:
    threshold: 100
  
  funlen:
    lines: 80
    statements: 40
    ignore-comments: true
  
  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: true
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
  
  goimports:
    local-prefixes: github.com/armaniacs/usacloud-update
  
  golint:
    min-confidence: 0.8
  
  gomnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
    ignored-numbers: 0,1,2
  
  govet:
    enable-all: true
    check-shadowing: true
  
  lll:
    line-length: 120
  
  maligned:
    suggest-new: true
  
  misspell:
    locale: US
    ignore-words:
      - usacloud
      - sakuracloud
  
  nakedret:
    max-func-lines: 30
  
  nestif:
    min-complexity: 4
  
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  
  unparam:
    check-exported: false
  
  unused:
    check-exported: false
  
  whitespace:
    multi-if: false
    multi-func: false

linters:
  disable-all: true
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    
    # Additional quality linters
    - cyclop
    - dupl
    - funlen
    - gocognit
    - goconst
    - gocyclo
    - gocritic
    - gofmt
    - goimports
    - gomnd
    - gosec
    - lll
    - misspell
    - nakedret
    - nestif
    - prealloc
    - unconvert
    - unparam
    - whitespace
    
    # Style and formatting
    - gofumpt
    - godot
    - godox
    - wsl

issues:
  exclude-use-default: false
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - cyclop
        - dupl
        - lll
    
    # Disable some checks for generated files
    - path: ".*\\.pb\\.go"
      linters:
        - gofumpt
        - goimports
    
    # Allow long lines in imports
    - source: "^//go:generate "
      linters:
        - lll

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false

severity:
  default-severity: error
  case-sensitive: false
  rules:
    - linters:
        - dupl
        - gomnd
        - goconst
      severity: warning
    - linters:
        - gosec
        - errcheck
        - staticcheck
      severity: error